/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Professional Moroccan-inspired colors
        moroccan: {
          teal: {
            DEFAULT: "#38B2AC",
            50: "#E6FFFA",
            100: "#B2F5EA",
            200: "#81E6D9",
            300: "#4FD1C7",
            400: "#38B2AC",
            500: "#319795",
            600: "#2C7A7B",
            700: "#285E61",
            800: "#234E52",
            900: "#1D4044",
          },
          sage: {
            DEFAULT: "#8BA178",
            50: "#F0F4EC",
            100: "#E1E9D9",
            200: "#C3D3B3",
            300: "#A5BD8D",
            400: "#8BA178",
            500: "#718E71",
            600: "#5A7A5A",
            700: "#436643",
            800: "#2C522C",
            900: "#1A3E1A",
          },
          terracotta: {
            DEFAULT: "#B7791F",
            50: "#FDF6E3",
            100: "#FAEDC7",
            200: "#F5DB8F",
            300: "#F0C957",
            400: "#D4A843",
            500: "#B7791F",
            600: "#9C651A",
            700: "#815115",
            800: "#663D10",
            900: "#4B290B",
          },
          gold: {
            DEFAULT: "#D4A843",
            50: "#FDF8E7",
            100: "#FAF0CF",
            200: "#F5E19F",
            300: "#F0D26F",
            400: "#D4A843",
            500: "#B8923A",
            600: "#9C7C31",
            700: "#806628",
            800: "#64501F",
            900: "#483A16",
          },
          burgundy: {
            DEFAULT: "#9C4221",
            50: "#FDF2F0",
            100: "#FCE4E1",
            200: "#F8C9C3",
            300: "#F4AEA5",
            400: "#E07A5F",
            500: "#CC5A37",
            600: "#B8472A",
            700: "#9C4221",
            800: "#7A331A",
            900: "#582413",
          },
          cream: {
            DEFAULT: "#F7F3E9",
            50: "#FEFDFB",
            100: "#F7F3E9",
            200: "#F0E7D3",
            300: "#E9DBBD",
            400: "#E2CFA7",
            500: "#DBC391",
            600: "#D4B77B",
            700: "#CDAB65",
            800: "#C69F4F",
            900: "#BF9339",
          },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: 0, transform: "translateX(-50px)" },
          "100%": { opacity: 1, transform: "translateX(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: 0, transform: "translateX(50px)" },
          "100%": { opacity: 1, transform: "translateX(0)" },
        },
        "moroccan-glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(56, 178, 172, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(56, 178, 172, 0.6)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
        "slide-in-left": "slide-in-left 0.6s ease-out",
        "slide-in-right": "slide-in-right 0.6s ease-out",
        "moroccan-glow": "moroccan-glow 3s ease-in-out infinite",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "sans-serif"],
        playfair: ["var(--font-playfair)", "serif"],
        sans: ["var(--font-inter)", "sans-serif"],
        serif: ["var(--font-playfair)", "serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
